apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: defaultstorageclass-protection
  labels:
    kubeaddons.mesosphere.io/name: defaultstorageclass-protection
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.1.0-1"
    appversion.kubeaddons.mesosphere.io/defaultstorageclass-protection: "0.1.0"
    # version 0.0.5 changed the selectors
    helm.kubeaddons.mesosphere.io/upgrade-strategy: "[{\"upgradeFrom\": \"<0.0.5\", \"strategy\": \"delete\"}]"
spec:
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: cert-manager
        kubeaddons.mesosphere.io/cert-manager: v1
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: vsphere
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: defaultstorageclass
    repo: https://mesosphere.github.io/charts/stable
    version: 0.1.0
    values: |
      ---
      issuer:
        name: kubernetes-ca
