apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: reloader
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: reloader
  annotations:
<<<<<<< HEAD
    catalog.kubeaddons.mesosphere.io/addon-revision: "v0.0.85-1"
    appversion.kubeaddons.mesosphere.io/reloader: "v0.0.85"
    values.chart.helm.kubeaddons.mesosphere.io/reloader: https://raw.githubusercontent.com/stakater/Reloader/a5bc586/deployments/kubernetes/chart/reloader/values.yaml
=======
    catalog.kubeaddons.mesosphere.io/addon-revision: "v0.0.99-1"
    appversion.kubeaddons.mesosphere.io/reloader: "v0.0.99"
    values.chart.helm.kubeaddons.mesosphere.io/reloader: https://raw.githubusercontent.com/stakater/Reloader/f2b4e8e/deployments/kubernetes/chart/reloader/values.yaml
>>>>>>> 05bef0e... Bump reloader to v0.0.99
    # Use delete strategy following a failure upgrading
    helm.kubeaddons.mesosphere.io/upgrade-strategy: "[{\"upgradeFrom\": \"<v0.0.79\", \"strategy\": \"delete\"}]"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  chartReference:
    chart: reloader
    repo: https://stakater.github.io/stakater-charts
<<<<<<< HEAD
    version: v0.0.85
=======
    version: v0.0.99
>>>>>>> 05bef0e... Bump reloader to v0.0.99
    values: |
      ---
      reloader:
        logFormat: json
        deployment:
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
