apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: reloader
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: reloader
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "v0.0.86-1"
    appversion.kubeaddons.mesosphere.io/reloader: "v0.0.86"
    values.chart.helm.kubeaddons.mesosphere.io/reloader: https://raw.githubusercontent.com/stakater/Reloader/c3b8af3/deployments/kubernetes/chart/reloader/values.yaml
    # Use delete strategy following a failure upgrading
    helm.kubeaddons.mesosphere.io/upgrade-strategy: "[{\"upgradeFrom\": \"<v0.0.79\", \"strategy\": \"delete\"}]"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  chartReference:
    chart: reloader
    repo: https://stakater.github.io/stakater-charts
    version: v0.0.86
    values: |
      ---
      reloader:
        logFormat: json
        deployment:
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
