apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: reloader
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: reloader
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "v0.0.68-1"
    appversion.kubeaddons.mesosphere.io/reloader: "v0.0.68"
    values.chart.helm.kubeaddons.mesosphere.io/reloader: https://raw.githubusercontent.com/stakater/Reloader/503e357/deployments/kubernetes/chart/reloader/values.yaml
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  chartReference:
    chart: reloader
    repo: https://stakater.github.io/stakater-charts
    version: v0.0.68
    values: |
      ---
      reloader:
        logFormat: json
        deployment:
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
