---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: fluentbit
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: fluentbit
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.3.7-1"
    appversion.kubeaddons.mesosphere.io/fluentbit: "1.3.7"
    values.chart.helm.kubeaddons.mesosphere.io/fluentbit: "https://raw.githubusercontent.com/helm/charts/d407562/stable/fluent-bit/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  requires:
    # This allows us to have fluentbit wait until ES is deployed and has the right configurations up, in particular
    # setting up index templates
    - matchLabels:
        kubeaddons.mesosphere.io/name: elasticsearch
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  chartReference:
    chart: stable/fluent-bit
    version: 2.8.17
    values: |
      audit:
        enable: true
        input:
          memBufLimit: 35MB
          parser: kubernetes-audit
          path: /var/log/kubernetes/audit/*.log
          bufferChunkSize: 5MB
          bufferMaxSize: 20MB
          skipLongLines: Off
          key: kubernetes-audit
      backend:
        es:
          host: elasticsearch-kubeaddons-client
          time_key: '@ts'
        type: es
      filter:
        mergeJSONLog: false
      input:
        tail:
          parser: cri
        systemd:
          enabled: true
          filters:
            systemdUnit: []
          stripUnderscores: true
      metrics:
        enabled: true
        service:
          labels:
            servicemonitor.kubeaddons.mesosphere.io/path: "api__v1__metrics__prometheus"
      tolerations:
        - effect: NoSchedule
          operator: Exists
      resources:
        limits:
          memory: 750Mi
        requests:
          # values extracted from a 1 output/1 input setup here:
          # https://github.com/fluent/fluent-bit-kubernetes-logging/blob/master/fluent-bit-daemonset-kafka-rest.yml
          # we double it for 1 output (es)/2 input (tail, systemd) as an approximation
          cpu: 200m
          memory: 200Mi
      parsers:
        enabled: true
        json:
          - name: kubernetes-audit
            timeKey: requestReceivedTimestamp
            timeKeep: On
            timeFormat: "%Y-%m-%dT%H:%M:%S.%L"
