apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: elasticsearchexporter
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: elasticsearchexporter
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.1.0-7"
    appversion.kubeaddons.mesosphere.io/elasticsearchexporter: "1.1.0"
    values.chart.helm.kubeaddons.mesosphere.io/elasticsearchexporter: "https://raw.githubusercontent.com/mesosphere/charts/b15fde2/stable/elasticsearch-exporter/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: vsphere
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: elasticsearch
  chartReference:
    chart: prometheus-elasticsearch-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: 4.4.0
    values: |
      ---
      # As defined in the readme file when migrating from old chart to new chart
      # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter
      # we should override the full name and name in order to do upgrades for services and deployments
      fullnameOverride: elasticsearchexporter-kubeaddons-elasticsearch-exporter
      nameOverride: elasticsearch-exporter
      es:
        uri: http://elasticsearch-kubeaddons-client:9200
      service:
        labels:
          servicemonitor.kubeaddons.mesosphere.io/path: "metrics"
        metricsPort:
          name: metrics
