apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: elasticsearchexporter
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: elasticsearchexporter
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.1.0-3"
    appversion.kubeaddons.mesosphere.io/elasticsearchexporter: "1.1.0"
    values.chart.helm.kubeaddons.mesosphere.io/elasticsearchexporter: "https://raw.githubusercontent.com/mesosphere/charts/73fba37/stable/elasticsearch-exporter/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: elasticsearch
  chartReference:
    chart: elasticsearch-exporter
    repo: https://mesosphere.github.io/charts/stable
    version: 3.7.0
    values: |
      ---
      es:
        uri: http://elasticsearch-kubeaddons-client:9200
      service:
        labels:
          servicemonitor.kubeaddons.mesosphere.io/path: "metrics"
        metricsPort:
          name: metrics
