version: 2
updates:
- package-ecosystem: gomod
  directory: "/test"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: k8s.io/client-go
    versions:
    - 0.20.2
    - 0.20.3
    - 0.20.4
    - 0.21.0
  - dependency-name: k8s.io/apimachinery
    versions:
    - 0.20.3
    - 0.20.4
    - 0.20.5
    - 0.21.0
  - dependency-name: k8s.io/api
    versions:
    - 0.20.3
    - 0.20.5
    - 0.21.0
  - dependency-name: github.com/mesosphere/kubeaddons
    versions:
    - 0.23.12
    - 0.23.13
    - 0.24.0
    - 0.24.1
    - 0.25.0
    - 0.26.0
  - dependency-name: sigs.k8s.io/controller-runtime
    versions:
    - 0.8.2
  - dependency-name: github.com/datawire/ambassador
    versions:
    - 1.11.1
  - dependency-name: github.com/mesosphere/ksphere-testing-framework
    versions:
    - 0.2.4
    - 0.2.5
    - 0.2.6
  - dependency-name: sigs.k8s.io/kind
    versions:
    - 0.10.0
