---
version: 2
mergeable:
  - when: pull_request.*
    do: and
    validate:
      - do: label
        and:
          - must_exclude:
              regex: 'needs documentation'
              message: 'This PR needs documentation.'
          - must_exclude:
              regex: 'needs release notes'
              message: 'This PR needs release notes.'
          - must_exclude:
              regex: 'do not merge'
              message: 'This PR is marked "do not merge".'
          - must_exclude:
              regex: 'wip'
              message: 'This PR is still in progress ("wip").'
      - do: milestone
        no_empty:
          enabled: true  # Cannot be empty when true.
          message: 'Milestone must be assigned before merging. Typically this is "release/next".'
      - do: description
        no_empty:
          enabled: true
        must_exclude:
          regex: '```release-note\s*```'
          regex_flag: m
          message: 'release-note block cannot be empty.'
        must_include:
          regex: '```release-note$(.|\r\n)+^```'
          regex_flag: mi
          message: |
            Must include release-note block:
              <code style="white-space: pre;">
              ```release-note
              note (or "none")
              ```
              </code>
      - do: dependent
        changed:
          file: test/go.mod
          files:
            - test/go.sum
        message: 'Please run "go mod tidy".'
