---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: external-dns
  labels:
    kubeaddons.mesosphere.io/name: external-dns
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.7.0-2"
    appversion.kubeaddons.mesosphere.io/external-dns: "0.7.0"
    values.chart.helm.kubeaddons.mesosphere.io/external-dns: "https://raw.githubusercontent.com/bitnami/charts/9eca03cb2f4b9d4a5b7e877711f810f9151ea2a3/bitnami/external-dns/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: false
    - name: azure
      enabled: false
    - name: gcp
      enabled: false
    - name: docker
      enabled: false
    - name: none
      enabled: false
  chartReference:
    repo: https://charts.bitnami.com/bitnami
    chart: external-dns
    version: 2.20.4
    values: |
      rbac:
        create: true
