---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: external-dns
  labels:
    kubeaddons.mesosphere.io/name: external-dns
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.7.0-4"
    appversion.kubeaddons.mesosphere.io/external-dns: "0.7.0"
    values.chart.helm.kubeaddons.mesosphere.io/external-dns: "https://raw.githubusercontent.com/mesosphere/charts/87aaac21e2833a3809323efd8787f71fa80ab023/stable/external-dns/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: false
    - name: azure
      enabled: false
    - name: gcp
      enabled: false
    - name: vsphere
      enabled: false
    - name: docker
      enabled: false
    - name: none
      enabled: false
  chartReference:
    repo: https://mesosphere.github.io/charts/stable
    chart: external-dns
    version: 2.20.5
    values: |
      rbac:
        create: true
      service:
        labels:
          servicemonitor.kubeaddons.mesosphere.io/path: "metrics"
