---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: nvidia
  labels:
    kubeaddons.mesosphere.io/name: nvidia
    kubeaddons.mesosphere.io/provides: nvidia
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.2.0-1"
    appversion.kubeaddons.mesosphere.io/nvidia: "0.2.0"
    values.chart.helm.kubeaddons.mesosphere.io/nvidia: "https://raw.githubusercontent.com/mesosphere/charts/master/staging/nvidia/values.yaml"
spec:
  namespace: kube-system
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: false
    - name: azure
      enabled: false
    - name: docker
      enabled: false
    - name: none
      enabled: false
  chartReference:
    chart: nvidia
    repo: https://mesosphere.github.io/charts/staging
    version: 0.2.0
    values: |
      ---
      nvidia-driver:
        image:
          tag: "418.87.01-centos7"
        resources:
          requests:
             cpu: 500m
             memory: 512Mi
        nodeSelector:
          konvoy.mesosphere.com/gpu-provider: NVIDIA
      nvidia-device-plugin:
        resources:
          limits:
             cpu: 200m
             memory: 128Mi
          requests:
             cpu: 100m
             memory: 128Mi
        nodeSelector:
          konvoy.mesosphere.com/gpu-provider: NVIDIA
        initContainers:
        - name: init-wait
          image: busybox
          command: ['sh', '-c', 'sleep 180']
      nvidia-dcgm-exporter:
        enabled: true
        namespace: kubeaddons
        nodeSelector:
          konvoy.mesosphere.com/gpu-provider: NVIDIA
        initContainers:
        - name: init-wait
          image: busybox
          command: ['sh', '-c', 'sleep 200']
      grafana:
        enabled: true
        namespace: kubeaddons
