apiVersion: kubeaddons.mesosphere.io/v1beta2
kind: Addon
metadata:
  name: gatekeeper
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: gatekeeper
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "3.3.0-1"
    appversion.kubeaddons.mesosphere.io/gatekeeper: "3.3.0"
    docs.kubeaddons.mesosphere.io/gatekeeper: "https://github.com/open-policy-agent/gatekeeper/blob/master/README.md"
    values.chart.helm.kubeaddons.mesosphere.io/gatekeeper: "https://raw.githubusercontent.com/mesosphere/charts/34a717f/staging/gatekeeper/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: cert-manager
        kubeaddons.mesosphere.io/cert-manager: v1
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: vsphere
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: gatekeeper
    repo: https://mesosphere.github.io/charts/staging
    version: 0.6.0
    valuesRemap:
      "mutations.enable": "gatekeeper.mutation.enable"
      "mutations.enablePodProxy": "gatekeeper.mutation.enablePodProxy"
      "proxySettings.noProxy": "gatekeeper.no-proxy"
      "proxySettings.httpProxy": "gatekeeper.http-proxy"
      "proxySettings.httpsProxy": "gatekeeper.https-proxy"
    values: |
      ---
      replicas: 2
      image:
        repository: openpolicyagent/gatekeeper
        release: v3.3.0
      webhook:
        certManager:
          enabled: true

      # ProxySettings
      proxySettings:
        noProxy:
        httpProxy:
        httpsProxy:

      # enable mutations
      mutations:
        enable: false
        enablePodProxy: false
