apiVersion: kubeaddons.mesosphere.io/v1beta2
kind: Addon
metadata:
  name: gatekeeper
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: gatekeeper
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "3.4.0-2"
    appversion.kubeaddons.mesosphere.io/gatekeeper: "3.4.0"
    docs.kubeaddons.mesosphere.io/gatekeeper: "https://github.com/open-policy-agent/gatekeeper/blob/master/README.md"
    values.chart.helm.kubeaddons.mesosphere.io/gatekeeper: "https://raw.githubusercontent.com/mesosphere/charts/333ebb9/staging/gatekeeper/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: cert-manager
        kubeaddons.mesosphere.io/cert-manager: v1
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: vsphere
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: gatekeeper
    repo: https://mesosphere.github.io/charts/staging
    version: 0.6.7
    valuesRemap:
      "mutations.enable": "gatekeeper.mutation.enable"
      "mutations.enablePodProxy": "gatekeeper.mutation.enablePodProxy"
      "mutations.excludeNamespacesFromProxy": "gatekeeper.mutation.excludeNamespacesFromProxy"
      "mutations.namespaceSelectorForProxy": "gatekeeper.mutation.namespaceSelectorForProxy"
      "mutations.podProxySettings.noProxy": "gatekeeper.mutation.no-proxy"
      "mutations.podProxySettings.httpProxy": "gatekeeper.mutation.http-proxy"
      "mutations.podProxySettings.httpsProxy": "gatekeeper.mutation.https-proxy"
    values: |
      ---
      replicas: 2
      webhook:
        certManager:
          enabled: true

      # enable mutations
      mutations:
        enable: false
        enablePodProxy: false

        podProxySettings:
          noProxy:
          httpProxy:
          httpsProxy:

        excludeNamespacesFromProxy: []
        namespaceSelectorForProxy: {}
