---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: gatekeeper
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: gatekeeper
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "3.0.4-3"
    appversion.kubeaddons.mesosphere.io/gatekeeper: "3.0.4-beta.1"
    docs.kubeaddons.mesosphere.io/gatekeeper: "https://github.com/open-policy-agent/gatekeeper/blob/master/README.md"
    values.chart.helm.kubeaddons.mesosphere.io/gatekeeper: "https://raw.githubusercontent.com/mesosphere/charts/f52ab9415b53aee946ff8e55a60b50be193b7ea7/staging/gatekeeper/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: cert-manager
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: gatekeeper
    repo: https://mesosphere.github.io/charts/staging
    version: 0.4.2
    values: |
      ---
      image:
        tag: v3.0.4-beta.1
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 200m
          memory: 300Mi
