---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: vsphere-csi-driver
  labels:
    kubeaddons.mesosphere.io/name: vsphere-csi-driver
    kubeaddons.mesosphere.io/provides: csi-driver
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.2.1-1"
    appversion.kubeaddons.mesosphere.io/vsphere-csi-driver: "2.0.1"
    values.chart.helm.kubeaddons.mesosphere.io/vsphere-csi-driver: "https://raw.githubusercontent.com/mesosphere/charts/5565912/stable/vsphere-csi-driver/values.yaml"
spec:
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: defaultstorageclass-protection
  kubernetes:
    minSupportedVersion: v1.16.0
  namespace: kube-system
  cloudProvider:
    - name: vsphere
      enabled: true
  chartReference:
    chart: vsphere-csi-driver
    repo: https://mesosphere.github.io/charts/stable
    version: 1.2.1
    values: |
      storageclass:
        # Fill it with your created and tagged vSphere Storage Policy
        # parameters:
        #   storagepolicyname: "Bronze NFS"
        parameters: {}
