---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: kiam
  labels:
    kubeaddons.mesosphere.io/name: kiam
    kubeaddons.mesosphere.io/provides: iam
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "3.5.0-1"
    appversion.kubeaddons.mesosphere.io/kiam: "3.5.0"
    values.chart.helm.kubeaddons.mesosphere.io/kiam: "https://raw.githubusercontent.com/uswitch/kiam/master/helm/kiam/values.yaml"
spec:
  namespace: kube-system
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
  chartReference:
    chart: kiam
    repo: https://uswitch.github.io/kiam-helm-charts/charts
    version: 5.7.0
    values: |
      ---
      server:
        affinity:
          nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: node-role.kubernetes.io/master
                 operator: Exists
        tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        sslCertHostPath: /etc/ssl/certs
        extraHostPathMounts:
        - name: pki
          hostPath: /etc/pki
          mountPath: /etc/pki
          readOnly: true
        # Secret name of server's TLS certificates
        tlsSecret: kiam-server-tls
        tlsCerts:
          certFileName: tls.crt
          keyFileName: tls.key
          caFileName: ca.crt
        # kube2iam-default
        assumeRoleArn: null
        # arn:aws:iam::0123456789:role/
        roleBaseArn: null
        # Session duration for STS tokens
        sessionDuration: 15m
        # Set this to true when running the servers on the same nodes as the agents
        useHostNetwork: false
      agent:
        affinity:
          nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: node-role.kubernetes.io/master
                 operator: DoesNotExist
        sslCertHostPath: /etc/ssl/certs
        extraHostPathMounts:
        - name: pki
          hostPath: /etc/pki
          mountPath: /etc/pki
          readOnly: true
        host:
          iptables: true
        # Secret name of agent's TLS certificates
        tlsSecret: kiam-agent-tls
        tlsCerts:
          certFileName: tls.crt
          keyFileName: tls.key
          caFileName: ca.crt
        whiteListRouteRegexp: ^.*(meta-data|dynamic/instance-identity/document).*$
