---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: awsebscsiprovisioner
  labels:
    kubeaddons.mesosphere.io/name: awsebscsiprovisioner
    kubeaddons.mesosphere.io/provides: storageclass
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.7.0-1"
    appversion.kubeaddons.mesosphere.io/awsebscsiprovisioner: "0.7.0"
    values.chart.helm.kubeaddons.mesosphere.io/awsebscsiprovisioner: "https://raw.githubusercontent.com/mesosphere/charts/ccf4f8a/stable/awsebscsiprovisioner/values.yaml"
spec:
  namespace: kube-system
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: defaultstorageclass-protection
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
  chartReference:
    version: 0.4.0
    chart: awsebscsiprovisioner
    repo: https://mesosphere.github.io/charts/stable
    values: |
      ---
      resizer:
        enabled: true
      snapshotter:
        enabled: true
      provisioner:
        enableVolumeScheduling: true
      storageclass:
        isDefault: true
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        type: gp2
        fstype: ext4
        iopsPerGB: null
        encrypted: false
        kmsKeyId: null
        allowedTopologies: []
        # - matchLabelExpressions:
        #   - key: topology.ebs.csi.aws.com/zone
        #     values:
        #     - us-west-2a
        #     - us-west-2b
        #     - us-west-2c
        allowVolumeExpansion: true
      # replicas of the CSI-Controller
      replicas: 1
      statefulSetCSIController:
      # if you want to use kube2iam or kiam roles define it here as podAnnotation for the CSI-Controller (statefulSet)
        podAnnotations: {}
      statefulSetCSISnapshotController:
        # if you want to use kube2iam or kiam roles define it here as podAnnotation for the CSI-Snapshot-Controller (statefulSet)
        podAnnotations: {}
      # Extra volume tags to attach to each dynamically provisioned volume.
      # ---
      # extraVolumeTags:
      #   key1: value1
      #   key2: value2
      extraVolumeTags: {}
