# ---------------------------------------------------------------------------------------------------
# EXPERIMENTAL: this addon is in experimental mode and only intended for use in testing environments.
# ---------------------------------------------------------------------------------------------------
apiVersion: kubeaddons.mesosphere.io/v1beta2
kind: ClusterAddon
metadata:
  name: kiali
  labels:
    kubeaddons.mesosphere.io/name: kiali
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "v1.53.0-1"
    appversion.kubeaddons.mesosphere.io/kiali-operator: "v1.53.0"
    appversion.kubeaddons.mesosphere.io/kiali: "1.29.0"
    stage.kubeaddons.mesosphere.io/kiali: Experimental
    endpoint.kubeaddons.mesosphere.io/kiali: "/ops/portal/kiali"
    docs.kubeaddons.mesosphere.io/kiali: "https://kiali.io/documentation/v1.53/"
    values.chart.helm.kubeaddons.mesosphere.io/kiali: "https://raw.githubusercontent.com/kiali/helm-charts/6006067/kiali-operator/values.yaml"
spec:
  namespace: istio-system
  kubernetes:
    minSupportedVersion: v1.19.0
  cloudProvider:
    - name: aws
      enabled: false
    - name: gcp
      enabled: false
    - name: azure
      enabled: false
    - name: docker
      enabled: false
    - name: vsphere
      enabled: false
    - name: none
      enabled: false
  chartReference:
    chart: kiali-operator
    repo: https://kiali.org/helm-charts/
    version: 1.53.0
    valuesRemap:
      "ingress.annotations.traefik\\.ingress\\.kubernetes\\.io/auth-url": "ingress.auth.auth-url"
    values: |
      image:
        repo: quay.io/kiali/kiali-operator
        tag: v1.29.0

      cr:
        create: true
        namespace: "istio-system"
        spec:
          auth:
            strategy: header
          server:
            web_root: /ops/portal/kiali
          external_services:
            grafana:
              in_cluster_url: http://prometheus-kubeaddons-grafana.kubeaddons:3000
            prometheus:
              url: http://prometheus-kubeaddons-prom-prometheus.kubeaddons:9090
            tracing:
              in_cluster_url: http://jaeger-kubeaddons-jaeger-operator-jaeger-query:16686
          deployment:
            image_version: v1.29.0
            version_label: v1.29.0
            accessible_namespaces:
            - '**'
            ingress_enabled: true
            override_ingress_yaml:
              metadata:
                annotations:
                  kubernetes.io/ingress.class: traefik
                  traefik.ingress.kubernetes.io/auth-response-headers: X-Forwarded-User,Authorization,Impersonate-User,Impersonate-Group
                  traefik.ingress.kubernetes.io/auth-type: forward
                  traefik.ingress.kubernetes.io/auth-url: http://traefik-forward-auth-kubeaddons.kubeaddons.svc.cluster.local:4181/
              spec:
                rules:
                - http:
                    paths:
                    - path:  /ops/portal/kiali
                      backend:
                        serviceName: kiali
                        servicePort: 20001
