# ---------------------------------------------------------------------------------------------------
# EXPERIMENTAL: this addon is in experimental mode and only intended for use in testing environments.
# ---------------------------------------------------------------------------------------------------
apiVersion: kubeaddons.mesosphere.io/v1beta2
kind: ClusterAddon
metadata:
  name: ambassador
  labels:
    kubeaddons.mesosphere.io/name: ambassador
    kubeaddons.mesosphere.io/provides: ingresscontroller
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.13.3-1"
    appversion.kubeaddons.mesosphere.io/ambassador: "1.13.3"
    docs.kubeaddons.mesosphere.io/ambassador: "https://www.getambassador.io/docs/"
    values.chart.helm.kubeaddons.mesosphere.io/ambassador: "https://raw.githubusercontent.com/datawire/ambassador/54d2411acd0e91264bebd9eb0dffa4942c540f05/charts/ambassador/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.17.11
  cloudProvider:
    - name: aws
      enabled: false
    - name: gcp
      enabled: false
    - name: azure
      enabled: false
    - name: docker
      enabled: false
    - name: vsphere
      enabled: false
# TODO: at the time of writing there are several changes in flight for our cert-manager addon and we're holding on cert-manager integration until a follow-up iteration
#  requires:
#    - matchLabels:
#        kubeaddons.mesosphere.io/name: cert-manager
  chartReference:
    chart: ambassador
    repo: https://getambassador.io
    version: 6.7.5
    values: |
      enableAES: false # use the OSS features
      image:
        repository: "datawire/ambassador" # use the OSS image
      rbac:
        create: true
      resources:
        limits:
          cpu: 1000m
        requests:
          cpu: 500m
