---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: azurediskprovisioner
  labels:
    kubeaddons.mesosphere.io/name: azurediskprovisioner
    kubeaddons.mesosphere.io/provides: storageclass
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.0-2"
    appversion.kubeaddons.mesosphere.io/azurediskprovisioner: "1.0"
    values.chart.helm.kubeaddons.mesosphere.io/azurediskprovisioner: "https://raw.githubusercontent.com/mesosphere/charts/efef983665c5bb1bef0901c4db26e90a32018cc8/stable/azurediskprovisioner/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: azure
      enabled: true
  chartReference:
    chart: azurediskprovisioner
    repo: https://mesosphere.github.io/charts/stable
    version: 0.1.1
