---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: kibana
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: kibana
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "6.8.2-3"
    appversion.kubeaddons.mesosphere.io/kibana: "6.8.2"
    endpoint.kubeaddons.mesosphere.io/kibana: "/ops/portal/kibana"
    docs.kubeaddons.mesosphere.io/kibana: "https://www.elastic.co/guide/en/kibana/6.8/index.html"
    values.chart.helm.kubeaddons.mesosphere.io/kibana: "https://raw.githubusercontent.com/helm/charts/09004fa332094693e2e5fcffe474622ba15491ae/stable/kibana/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: elasticsearch
  chartReference:
    chart: stable/kibana
    version: 3.2.5
    values: |
      ---
      image:
        tag: "6.8.2"
      files:
        kibana.yml:
          ## Default Kibana configuration from kibana-docker.
          elasticsearch.url: http://elasticsearch-kubeaddons-client:9200
          ## Ref: https://www.elastic.co/guide/en/kibana/current/settings.html
          server.basePath: /ops/portal/kibana
      serviceAccount:
        create: true
      service:
        type: ClusterIP
        externalPort: 5601
        internalPort: 5601
        labels:
          servicemonitor.kubeaddons.mesosphere.io/path: "prometheus__metrics"
      resources:
        # need more cpu upon initialization, therefore burstable class
        limits:
          cpu: 1000m
        requests:
          cpu: 100m
      plugins:
        # to avoid needing to download any plugins at runtime, use a container and a shared volume
        # do not enable the plugins here, instead rebuild the mesosphere/kibana-plugins image with the new plugins
        enabled: false
        values:
          - kibana-prometheus-exporter,6.8.2,https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/6.8.2/kibana-prometheus-exporter-6.8.2.zip
      extraContainers: |
        - name: initialize-kibana-index
          image: mesosphere/kubeaddons-addon-initializer:v0.1.5
          command: ["/bin/bash", "-c", "addon-initializer kibana && sleep infinity"]
          env:
          - name: "KIBANA_NAMESPACE"
            value: "kubeaddons"
          - name: "KIBANA_SERVICE_NAME"
            value: "kibana-kubeaddons"
      initContainers:
        # from https://github.com/mesosphere/kubeaddons-sidecars
        - name: kibana-plugins-install
          image: mesosphere/kibana-plugins:v6.8.2
          command: ["/bin/sh", "-c", "cp -a /usr/share/kibana/plugins/. /usr/share/kibana/shared-plugins/"]
          volumeMounts:
          - name: plugins
            mountPath: /usr/share/kibana/shared-plugins/
      extraVolumes:
        - name: plugins
          emptyDir: {}
      extraVolumeMounts:
        - mountPath: /usr/share/kibana/plugins/
          name: plugins
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.frontend.rule.type: PathPrefixStrip
          traefik.ingress.kubernetes.io/auth-response-headers: X-Forwarded-User,Authorization,Impersonate-User,Impersonate-Group
          traefik.ingress.kubernetes.io/auth-type: forward
          traefik.ingress.kubernetes.io/auth-url: http://traefik-forward-auth-kubeaddons.kubeaddons.svc.cluster.local:4181/
          traefik.ingress.kubernetes.io/priority: "2"
        hosts:
          - "/ops/portal/kibana"
      dashboardImport:
        enabled: true
        dashboards:
          audit-logs-dashboards: '{"objects":[{"id":"19422f60-93e2-11e8-83ef-b5593250e6b7","type":"dashboard","attributes":{"title":"Audit-Dashboard","hits":0,"description":"Dashboard for Audit-Logs","panelsJSON":"[{\"panelIndex\": \"1\",\"gridData\": {\"x\": 0,\"y\": 10,\"w\": 50,\"h\": 30,\"i\": \"1\"},\"id\": \"bb4f4e80-93e9-11e8-83ef-b5593250e6b7\",\"type\": \"search\",\"version\": \"6.8.2\",\"embeddableConfig\": {\"columns\": [\"objectRef.namespace\",\"user.username\",\"sourceIPs\",\"verb\",\"objectRef.resource\",\"requestURI\"]}},{\"panelIndex\": \"2\",\"gridData\": {\"x\": 0,\"y\": 0,\"w\": 9,\"h\": 9,\"i\": \"2\"},\"embeddableConfig\": {\"spy\": null,\"vis\": {\"legendOpen\": true}},\"id\": \"07098510-93cb-11ea-a17b-e52b18339f68\",\"type\": \"visualization\",\"version\": \"6.8.2\"},{\"panelIndex\": \"3\",\"gridData\": {\"x\": 9,\"y\": 0,\"w\": 9,\"h\": 9,\"i\": \"3\"},\"embeddableConfig\": {\"spy\": null,\"vis\": {\"legendOpen\": true}},\"id\": \"324f3710-93eb-11e8-83ef-b5593250e6b7\",\"type\": \"visualization\",\"version\": \"6.8.2\"},{\"panelIndex\":\"4\",\"gridData\": {\"x\": 18,\"y\": 0,\"w\": 9,\"h\": 9,\"i\": \"4\"},\"id\": \"429087b0-9584-11e8-a471-e1cc12dab5c6\",\"type\": \"visualization\",\"version\": \"6.8.2\"},{\"panelIndex\":\"5\",\"gridData\": {\"x\": 27,\"y\": 0,\"w\": 9,\"h\": 9,\"i\": \"5\"},\"version\": \"6.8.2\",\"type\": \"visualization\",\"id\": \"38b93150-9585-11e8-a471-e1cc12dab5c6\"},{\"panelIndex\":\"6\",\"gridData\": {\"x\": 36,\"y\": 0,\"w\": 9,\"h\": 9,\"i\": \"6\"},\"version\": \"6.8.2\",\"type\": \"visualization\",\"id\": \"138c2220-9585-11e8-a471-e1cc12dab5c6\"}]","optionsJSON":"{\"darkTheme\":true,\"hidePanelTitles\":false,\"useMargins\":false}","version":1,"timeRestore":false,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"query\":{\"language\":\"lucene\",\"query\":\"\"},\"filter\":[],\"highlightAll\":true,\"version\":true}"}}},{"id":"bb4f4e80-93e9-11e8-83ef-b5593250e6b7","type":"search","attributes":{"title":"Audit-Search","description":"","hits":0,"columns":["objectRef.namespace","user.username","sourceIPs","verb","objectRef.resource","requestURI"],"sort":["@timestamp","desc"],"version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"index\":\"kubernetes_cluster\",\"highlightAll\":true,\"version\":true,\"query\":{\"query\":\"apiVersion:\\\"audit.k8s.io/v1\\\"\",\"language\":\"lucene\"},\"filter\":[]}"}}},{"id":"dbd12d90-93c9-11ea-a17b-e52b18339f68","type":"search","attributes":{"title":"Audit-Search: Pods","description":"Audit log search for pods with a `namespace that exists` filter applied","hits":0,"columns":["objectRef.namespace","user.username","sourceIPs","verb","requestURI"],"sort":["@timestamp","desc"],"version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"index\":\"kubernetes_cluster\",\"highlightAll\":true,\"version\":true,\"query\":{\"query\":\"apiVersion:\\\"audit.k8s.io/v1\\\" AND objectRef.resource:\\\"pods\\\"\",\"language\":\"lucene\"},\"filter\":[{\"meta\":{\"index\":\"kubernetes_cluster\",\"negate\":false,\"disabled\":false,\"alias\":null,\"type\":\"exists\",\"key\":\"objectRef.namespace\",\"value\":\"exists\"},\"exists\":{\"field\":\"objectRef.namespace\"},\"$state\":{\"store\":\"appState\"}}]}"}}},{"id":"429087b0-9584-11e8-a471-e1cc12dab5c6","type":"visualization","attributes":{"title":"Audit-Visualization: Source-Ips","visState":"{\"title\":\"audit-source-ips-visualization\",\"type\":\"pie\",\"params\":{\"type\":\"pie\",\"addTooltip\":true,\"addLegend\":true,\"legendPosition\":\"right\",\"isDonut\":false,\"labels\":{\"show\":false,\"values\":true,\"last_level\":true,\"truncate\":100}},\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":\"2\",\"enabled\":true,\"type\":\"terms\",\"schema\":\"segment\",\"params\":{\"field\":\"sourceIPs.keyword\",\"otherBucket\":false,\"otherBucketLabel\":\"Other\",\"missingBucket\":false,\"missingBucketLabel\":\"Missing\",\"size\":100,\"order\":\"desc\",\"orderBy\":\"1\"}}]}","uiStateJSON":"{}","description":"","savedSearchId":"bb4f4e80-93e9-11e8-83ef-b5593250e6b7","version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"filter\":[],\"query\":{\"query\":\"\",\"language\":\"lucene\"}}"}}},{"id":"138c2220-9585-11e8-a471-e1cc12dab5c6","type":"visualization","attributes":{"title":"Audit-Visualization: Resource","visState":"{\"title\":\"audit-resource-visualization\",\"type\":\"pie\",\"params\":{\"type\":\"pie\",\"addTooltip\":true,\"addLegend\":true,\"legendPosition\":\"right\",\"isDonut\":false,\"labels\":{\"show\":false,\"values\":true,\"last_level\":true,\"truncate\":100}},\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":\"2\",\"enabled\":true,\"type\":\"terms\",\"schema\":\"segment\",\"params\":{\"field\":\"objectRef.resource.keyword\",\"otherBucket\":false,\"otherBucketLabel\":\"Other\",\"missingBucket\":false,\"missingBucketLabel\":\"Missing\",\"size\":100,\"order\":\"desc\",\"orderBy\":\"1\"}}]}","uiStateJSON":"{}","description":"","savedSearchId":"bb4f4e80-93e9-11e8-83ef-b5593250e6b7","version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"filter\":[],\"query\":{\"query\":\"\",\"language\":\"lucene\"}}"}}},{"id":"38b93150-9585-11e8-a471-e1cc12dab5c6","type":"visualization","attributes":{"title":"Audit-Visualization: Verb","visState":"{\"title\":\"audit-verb-visualization\",\"type\":\"pie\",\"params\":{\"type\":\"pie\",\"addTooltip\":true,\"addLegend\":true,\"legendPosition\":\"right\",\"isDonut\":false,\"labels\":{\"show\":false,\"values\":true,\"last_level\":true,\"truncate\":100}},\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":\"2\",\"enabled\":true,\"type\":\"terms\",\"schema\":\"segment\",\"params\":{\"field\":\"verb.keyword\",\"otherBucket\":false,\"otherBucketLabel\":\"Other\",\"missingBucket\":false,\"missingBucketLabel\":\"Missing\",\"size\":100,\"order\":\"desc\",\"orderBy\":\"1\"}}]}","uiStateJSON":"{}","description":"","savedSearchId":"bb4f4e80-93e9-11e8-83ef-b5593250e6b7","version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"filter\":[],\"query\":{\"query\":\"\",\"language\":\"lucene\"}}"}}},{"id":"324f3710-93eb-11e8-83ef-b5593250e6b7","type":"visualization","attributes":{"title":"Audit-Visualization: User","visState":"{\"title\":\"audit-user-visualization\",\"type\":\"pie\",\"params\":{\"addLegend\":true,\"addTooltip\":true,\"isDonut\":false,\"labels\":{\"last_level\":true,\"show\":false,\"truncate\":100,\"values\":true},\"legendPosition\":\"right\",\"type\":\"pie\"},\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"schema\":\"metric\",\"params\":{\"customLabel\":\"Username\"}},{\"id\":\"2\",\"enabled\":true,\"type\":\"terms\",\"schema\":\"segment\",\"params\":{\"field\":\"user.username.keyword\",\"otherBucket\":false,\"otherBucketLabel\":\"Other\",\"missingBucket\":false,\"missingBucketLabel\":\"Missing\",\"size\":100,\"order\":\"desc\",\"orderBy\":\"1\",\"customLabel\":\"Username\"}}]}","uiStateJSON":"{\"vis\":{\"legendOpen\":true},\"spy\":null}","description":"","savedSearchId":"bb4f4e80-93e9-11e8-83ef-b5593250e6b7","version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"filter\":[],\"query\":{\"query\":\"\",\"language\":\"lucene\"}}"}}},{"id":"07098510-93cb-11ea-a17b-e52b18339f68","type":"visualization","attributes":{"title":"Audit-Visualization: Namespace","visState":"{\"title\":\"audit-namespace\",\"type\":\"pie\",\"params\":{\"addLegend\":true,\"addTooltip\":true,\"isDonut\":false,\"labels\":{\"last_level\":true,\"show\":false,\"truncate\":100,\"values\":true},\"legendPosition\":\"right\",\"type\":\"pie\"},\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"schema\":\"metric\",\"params\":{\"customLabel\":\"Namespace\"}},{\"id\":\"2\",\"enabled\":true,\"type\":\"terms\",\"schema\":\"segment\",\"params\":{\"field\":\"objectRef.namespace.keyword\",\"otherBucket\":false,\"otherBucketLabel\":\"Other\",\"missingBucket\":false,\"missingBucketLabel\":\"Missing\",\"size\":100,\"order\":\"desc\",\"orderBy\":\"1\",\"customLabel\":\"Namespace\"}}]}","uiStateJSON":"{\"vis\":{\"legendOpen\":true},\"spy\":null}","description":"","savedSearchId":"bb4f4e80-93e9-11e8-83ef-b5593250e6b7","version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"filter\":[],\"query\":{\"query\":\"\",\"language\":\"lucene\"}}"}}}]}'
