apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: cert-manager
  labels:
    kubeaddons.mesosphere.io/name: cert-manager
    kubeaddons.mesosphere.io/cert-manager: v1
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.3-7"
    appversion.kubeaddons.mesosphere.io/cert-manager: "1.0.3"
    docs.kubeaddons.mesosphere.io/cert-manager: "https://cert-manager.io/docs/release-notes/release-notes-1.0/"
    values.chart.helm.kubeaddons.mesosphere.io/cert-manager: "https://raw.githubusercontent.com/mesosphere/charts/5701849/stable/cert-manager-setup/values.yaml"
    helm.kubeaddons.mesosphere.io/upgrade-strategy: "[{\"upgradeFrom\": \"<0.2.0\", \"strategy\": \"delete\"}]"
spec:
  namespace: cert-manager
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: cert-manager-setup
    repo: https://mesosphere.github.io/charts/stable
    version: 0.2.6
    values: |
      ---
      upgradeImage: "mesosphere/kubeaddons-addon-initializer:v0.4.2"
      issuers:
        - name: kubernetes-root-issuer
          secretName: kubernetes-root-ca

      certificates:
        - name: kubernetes-intermediate-ca
          secretName: kubernetes-intermediate-ca
          issuerRef:
            name: kubernetes-root-issuer
            kind: Issuer
          # These are the default usages for reference
          usages:
            - "digital signature"
            - "key encipherment"
          commonName: cert-manager
          duration: 87600h
          dnsNames: []

      clusterissuers:
        - name: kubernetes-ca
          spec:
            ca:
              secretName: kubernetes-intermediate-ca
