---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: external-dns
  labels:
    kubeaddons.mesosphere.io/name: external-dns
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.5.18-1"
    appversion.kubeaddons.mesosphere.io/external-dns: "0.5.18"
    values.chart.helm.kubeaddons.mesosphere.io/external-dns: "https://raw.githubusercontent.com/helm/charts/4f38b11/stable/external-dns/values-production.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
      values: |
        aws:
          region:
        domainFilters: []
    - name: azure
      enabled: false
    - name: gcp
      enabled: false
    - name: docker
      enabled: false
    - name: none
      enabled: false
  chartReference:
    chart: stable/external-dns
    version: 2.16.1
    values: |
      rbac:
        create: true
