---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: opsportal
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: opsportal
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.0-5"
    appversion.kubeaddons.mesosphere.io/opsportal: "1.0.0"
    endpoint.kubeaddons.mesosphere.io/opsportal: /ops/portal/
    values.chart.helm.kubeaddons.mesosphere.io/opsportal: "https://raw.githubusercontent.com/mesosphere/charts/4155f480571eaf82c64ddd63d3d334b1105d0591/stable/opsportal/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: opsportal
    repo: https://mesosphere.github.io/charts/stable
    version: 0.1.34
    values: |
      ---
      landing:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      opsportal:
        ingress:
          paths: []
