---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: dispatch
  labels:
    kubeaddons.mesosphere.io/name: dispatch
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.3.5-1"
    appversion.kubeaddons.mesosphere.io/dispatch: "0.3.5"
    endpoint.kubeaddons.mesosphere.io/dispatch: /dispatch/tekton/
    docs.kubeaddons.mesosphere.io/dispatch: "https://beta-dispatch.d2iq.com/"
    appversion.kubeaddons.mesosphere.io/argo-cd: "1.2.0"
    endpoint.kubeaddons.mesosphere.io/argo-cd: /dispatch/argo-cd
    docs.kubeaddons.mesosphere.io/argo-cd: "https://argoproj.github.io/argo-cd/user-guide/"
    values.chart.helm.kubeaddons.mesosphere.io/dispatch: "https://raw.githubusercontent.com/mesosphere/charts/master/stable/dispatch/values.yaml"
spec:
  namespace: dispatch
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: false
    - name: azure
      enabled: false
    - name: gcp
      enabled: false
    - name: docker
      enabled: false
    - name: none
      enabled: false
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: prometheus
  chartReference:
    chart: dispatch
    repo: https://mesosphere.github.io/charts/stable
    version: 0.3.7
    values: |
      ---
      argo-cd:
        prometheus:
          enabled: true
          release: prometheus-kubeaddons

      prometheus:
        enabled: true
        release: prometheus-kubeaddons
