# --------------------------------------------------------------------------------------------------
# EXPERIMENTAL: this addon is in experimental mode and only intended for use in testing environments.
# ---------------------------------------------------------------------------------------------------
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: istio
  labels:
    kubeaddons.mesosphere.io/name: istio
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.11.5-1"
    appversion.kubeaddons.mesosphere.io/istio: "1.11.5"
    docs.kubeaddons.mesosphere.io/istio: "https://istio.io/docs/"
    values.chart.helm.kubeaddons.mesosphere.io/istio: "https://raw.githubusercontent.com/mesosphere/charts/7e5e024/staging/istio/values.yaml"
spec:
  namespace: istio-system
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: cert-manager
        kubeaddons.mesosphere.io/cert-manager: v1
  kubernetes:
    minSupportedVersion: v1.16.0
  cloudProvider:
    - name: aws
      enabled: false
    - name: azure
      enabled: false
    - name: gcp
      enabled: false
    - name: vsphere
      enabled: false
    - name: docker
      enabled: false
    - name: none
      enabled: false
  chartReference:
    chart: istio
    repo: https://mesosphere.github.io/charts/staging
    version: 1.11.5
    values: |
      istioOperator:
        components:
          ingressGateways:
          - enabled: true
            k8s:
              hpaSpec:
                minReplicas: 2
            name: istio-ingressgateway
          pilot:
            k8s:
              hpaSpec:
                minReplicas: 2
