apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: nvidia
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: nvidia
    kubeaddons.mesosphere.io/provides: nvidia
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.2.2-2"
    appversion.kubeaddons.mesosphere.io/nvidia: "0.2.0"
    values.chart.helm.kubeaddons.mesosphere.io/nvidia: "https://raw.githubusercontent.com/mesosphere/charts/290c2da/staging/nvidia/values.yaml"
    # The nvidia addon requires its underlying driver to be completely removed before adding an upgraded one, as two versions of the driver can no cleanly
    # co-exist in version v0.3.x of the chart. For this reason we do a delete upgrade to ensure the driver is fully purged before installing the new one.
    helm.kubeaddons.mesosphere.io/upgrade-strategy: '[{"upgradeFrom": "<=0.4.0", "strategy": "delete"}]'
    helm2.kubeaddons.mesosphere.io/upgrade-strategy: '[{"upgradeFrom": "<=0.4.0", "strategy": "delete"}]'
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: false
    - name: azure
      enabled: false
    - name: docker
      enabled: false
    - name: none
      enabled: false
  chartReference:
    chart: nvidia
    repo: https://mesosphere.github.io/charts/staging
    version: 0.4.2
    values: |
      ---
      grafana:
        enabled: true
      nvidia-dcgm-exporter:
        enabled: true
        nodeSelector:
          konvoy.mesosphere.com/gpu-provider: NVIDIA
      nvidia-device-plugin:
        enabled: true
        resources:
          limits:
             cpu: 200m
             memory: 128Mi
          requests:
             cpu: 100m
             memory: 128Mi
        nodeSelector:
          konvoy.mesosphere.com/gpu-provider: NVIDIA
